### ISSUE TITLE
Signature validation fails

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#8] opened 2019-11-25 17:34 UTC
Hi,

It looks like the signature validation fails.  I have the "webhook_secret" set in conf.json and this is the same secret as configured in the Integration Profile.  Here is the message from the logs:

2019-11-25 17:13:45,386 http-nio-8080-exec-18id INFO   WebhookServlet  78: un validate signature

Could you please assist in trouble shooting? 

I did read in a post that webhooks are sent with: 
"Content-Type: application/json;charset=UTF-8
rather than
Content-Type: application/json"
(https://sbprojects.statsbiblioteket.dk/stash/projects/SWHL/repos/web-hooker/commits/e5c0855e1fe03f476cae13aa3edc7fbeca09af92)

It appears that the request is coming with "content-type = application/json".

thanks,
Kathy

**Comment by ori229** [comment] 2019-11-26 08:12
That was a hard one... caused by a white space...
https://stackoverflow.com/a/20041648/11903544
Fixed now.

**Closed by ori229** 2019-11-26 08:12 UTC
